### ISSUE TITLE
能否在jdk源代码中添加System.out.println语句

### ISSUE THREAD

**Issue by vitahlin** [kangjianwei/OpenJDK-11#10]
你好，最近在学习jdk源码，遇到了一点问题。
比如说我写了一个测试类：
```java
 public static void main(String[] args) {
        String string = new String();
        System.out.println(string.length());
    }
```

然后修改jdk的string源代码：
```java
   public String() {
        System.out.println("abc");
        this.value = "a".value;
    }
```

这时候我发现，`abc`并不会打印。

你的项目能否实现对jdk代码的自行修改并输出呢？
感谢🙏

**Comment by kangjianwei** [comment]
@vitahlin 
对自己代码的编译是建立在已有JDK的基础上的。所以如果是修改JDK源码的话，则必须对整个JDK源码进行重新编译后再引入才能生效。这显然是个很费时的操作，不建议这么做。
如果只是想看到JDK内部的一些执行流程，那么以IDEA为例，配合使用条件断点和日志断点就可以做到了，具体使用方式可以自行搜索，网上很多IDEA的断点教程。

**Comment by vitahlin** [comment]
了解了，感谢。🙏
