### ISSUE TITLE
添加忽略文件，改造成maven项目

### ISSUE THREAD

**Issue by 1228857713** [kangjianwei/OpenJDK-11#11]
是否可以添加忽略文件，改造成maven项目

**Comment by kangjianwei** [comment]
感觉必要性不强啊，因为这里都是JDK源码，不涉及别的框架代码...

**Comment by 1228857713** [comment]
.gitignore 文件还是要的吧

**Comment by kangjianwei** [comment]
.gitignore必要性也不大，因为这里不会编译，基本也不会引入其他文件。
当然，如果你乐意，可以做进一步改造。
