### ISSUE TITLE
关联jdk后，文件冲突

### ISSUE THREAD

**Issue by glucky0898** [kangjianwei/OpenJDK-11#13]
在本地用idea打开并关联了jdk11，切换test分支，运行测试用例时报错。。错误如下图
![image](https://user-images.githubusercontent.com/41634772/115530022-fb1a6480-a2c5-11eb-87e1-c16c3c0288e7.png)
打开文件后，有波浪提示错误，按照idea提供的解决方法，添加了add-exports命令 如下图
![2](https://user-images.githubusercontent.com/41634772/115652776-74ff2c00-a360-11eb-8262-138f3e6b693a.PNG)
运行测试文件后依然报同样的错误，请教下怎么解决

**Comment by kangjianwei** [comment]
建议检查关联JDK的方式。
另外，后续会把源码和测试用例分开存放，以避免类似的问题。
