### ISSUE TITLE
maste分支拉去了代码 idea打开后  发现类缺失代码块！

### ISSUE THREAD

**Issue by ifeifly** [kangjianwei/OpenJDK-11#16]
![image](https://user-images.githubusercontent.com/44634609/145577921-5485e812-b832-4381-9505-38504e3722ee.png)
Bits.BUFFER_POOL 没有....

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！

**Comment by kangjianwei** [comment]
不要引入外部JDK!
