### ISSUE TITLE
源码注释显示问题？

### ISSUE THREAD

**Issue by gangyahaidao** [kangjianwei/OpenJDK-11#3]
你好，最近正在研究源码，你写的内容帮助很大，正在学习，多谢了，在看Objects类的源码时看到文件的注释中有黑色的条块，不知是什么原因引起的
![image](https://user-images.githubusercontent.com/25075558/59238359-67d76900-8c30-11e9-9b28-af89348c8458.png)

**Comment by kangjianwei** [comment]
@gangyahaidao 这个是故意的，为了在上下翻看源码时快速定位边界...

**Comment by gangyahaidao** [comment]
好主意
