### ISSUE TITLE
测试报错问题

### ISSUE THREAD

**Issue by ZhangTeng2017** [kangjianwei/OpenJDK-11#4]
为什么我切换到test分支运行代码时有如下的错误，看错误意思是jar的问题？因为第一次使用idea,还请大佬帮忙指导一下。多谢了🙏🙏🙏
<img width="1792" alt="截屏2019-12-24下午10 44 06" src="https://user-images.githubusercontent.com/30196644/71417238-3fc8c800-269f-11ea-8b97-c395cedce89f.png">

**Comment by kangjianwei** [comment]
@ZhangTeng2017 报错那个包下应该有个叫hello的jar包，你看下是不是缺那个...我刚切换到test分支，可以运行的...如果你那还不能运行，有没有更具体的信息...

**Comment by ZhangTeng2017** [comment]
<img width="1792" alt="截屏2020-01-04下午9 41 19" src="https://user-images.githubusercontent.com/30196644/71766447-0c0d5e00-2f3b-11ea-9bf6-5ce9d4c12740.png">
这是具体的报错信息，我看这里面的lib中有jar包，导入之后还是报错了

**Comment by kangjianwei** [comment]
@ZhangTeng2017 

你看一下依赖里导包了没？

![Snipaste_2020-01-05_16-40-37](https://user-images.githubusercontent.com/43163220/71777416-86d98600-2fda-11ea-9bd9-ea8b873f4c0f.png)

**Comment by ZhangTeng2017** [comment]
这里面有导入
<img width="1792" alt="截屏2020-01-05下午8 16 34" src="https://user-images.githubusercontent.com/30196644/71780028-543e8600-2ff8-11ea-9e92-f16a70ba23d4.png">

**Comment by kangjianwei** [comment]
@ZhangTeng2017 

我看你这个包不像导进去的样子，如果导进去了，在lib下会显示它的内容，而不是作为一个整体显示...左边还提示Problems，排查一下...

![Snipaste_2020-01-05_21-22-39](https://user-images.githubusercontent.com/43163220/71780769-af28ab00-3001-11ea-9501-8d5f166363dc.png)

**Comment by ZhangTeng2017** [comment]
<img width="1792" alt="截屏2020-01-05下午9 32 46" src="https://user-images.githubusercontent.com/30196644/71780880-f5cad500-3002-11ea-964b-62bfd0d2c42a.png">
那个jar重新导入没有问题了，这个问题是不是要按照那两张图片设置一下Java参数

**Comment by kangjianwei** [comment]
@ZhangTeng2017 

不是，这个错误不是那个参数引起的，因为这里没有引用到未导出的模块。

**Comment by ZhangTeng2017** [comment]
多谢，最终按照设置了一下Javac的参数，就是编译时要加一个路径。又按照下面的改了一下project lanlanguage leve https://stackoverflow.com/questions/29888592/errorjava-javactask-source-release-8-requires-target-release-1-8。现在可以完美运行了，🙏

**Comment by wsuo** [comment]
![image](https://user-images.githubusercontent.com/49612558/79294162-19f25800-7f08-11ea-952b-883136f6032b.png)
这怎么回事啊? 我已经导入了 hello 包了.
![image](https://user-images.githubusercontent.com/49612558/79294212-32fb0900-7f08-11ea-9b81-1df762d67830.png)

**Comment by ZhangTeng2017** [comment]
能不能提供报错位置代码的截图

**Comment by ZhangTeng2017** [comment]
你好，能不能提供一下报错位置代码的截图
