### ISSUE TITLE
可否添加JDK1.7版本

### ISSUE THREAD

**Issue by mrfsong363** [kangjianwei/OpenJDK-11#5]

**Comment by kangjianwei** [comment]
@mrfsong 

大面上来看，现在开发基本都普及到JDK1.8了，所以个人感觉没有再看1.7的必要。

有时候感觉阅读1.8的代码难度很大，其实是因为1.8新增了函数表达式与流式API。所以，建议先把这部分新特性攻克后再去看1.8的代码，就会觉得1.8跟1.7相比也没那么难了。

再往后观察，JDK 9又是一个大的分水岭，因为加入了模块化。这里之所以选择阅读JDK 11，是因为JDK 11是JDK 9之后的第一个长期支持版本。在JDK 11里，新增的模块化内容频繁出现在反射相关的代码中，但对其他大部分代码而言，其实影响不大。

总而言之，现在选择学习JDK 11，难度肯定是比JDK 1.7大，但是并不会有想象中的那么大。而且从长远看，学习JDK 11也是值得的，因为新增的特性迟早需要克服。
