### ISSUE TITLE
Class类isLocalOrAnonymousClass翻译有误

### ISSUE THREAD

**Issue by tomato-cc** [kangjianwei/OpenJDK-11#7]
*/
    // X.class.isLocalClass() ==> 判断X是否为方法内部类
    public boolean isLocalClass() {
        return isLocalOrAnonymousClass() && (isArray() || getSimpleBinaryName0() != null);
    }

应该为‘本地类’

**Comment by kangjianwei** [comment]
@tomato-cc 嗯，其实这个翻译成"本地类"也更让人迷惑，正确的译法应该是"局部类"。
"局部"通常是指方法或其他由花括号围成的普通块，"局部类"就是指声明在"局部"范围中的类。
因为"局部类"最常见的表现就是声明在方法中，其他声明在普通块中的类基本没遇到过，所以当时写注释的时候直接写了"方法内部类"。
在下一个快照中会对此注释进行更新，重新标记为"局部类"。
